name: Non Ascii Spotter

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

inputs:
  path:
    description: 'The path to search for non-ascii characters'
    required: true
    default: 'hello.c'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jamieeeeeeeeeeeeeeee/actions:latest
    steps:
    - uses: actions/checkout@v4
    - name: Search for non-ascii characters
      run: ${{ inputs.path }}