name: Non Ascii Spotter

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

inputs:
  path:
    description: 'The path to search for non-ascii characters'
    required: true
    default: 'hello.c'

runs:
    using: 'docker'
    image: docker://ghcr.io/jamieeeeeeeeeeeeeeee/actions@main
    args:
      - test.txt