name: Non Ascii Spotter

on:
  push:
    branches:
      push: ["main"]
      
      workflow_dispatch:

inputs:
  path:
    description: 'The path to search for non-ascii characters'
    required: true
    default: 'hello.c'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Search for non-ascii characters
      run: action ${{ inputs.path }}